insert into public.jobs (
  title,
  slug,
  description,
  type,
  sector_slug,
  sector_label,
  source_kind,
  source_name,
  organization_name,
  location_city,
  external_url,
  status,
  is_verified,
  is_premium,
  published_at
)
values
  (
    'Assistant(e) Commercial(e)',
    'assistant-commercial-educarriere',
    'Offre sourcee depuis Educarriere pour un profil commercial oriente prospection et suivi client.',
    'job',
    'commerce',
    'Commerce',
    'partner_site',
    'Educarriere.ci',
    'Entreprise privee',
    'Abidjan',
    'https://educarriere.ci',
    'published',
    true,
    false,
    timezone('utc', now()) - interval '2 days'
  ),
  (
    'Technicien Transit - Interim',
    'technicien-transit-interim-educarriere',
    'Mission terrain autour du transit et du suivi documentaire import-export.',
    'job',
    'transit',
    'Transit',
    'partner_site',
    'Educarriere.ci',
    'Cabinet RH',
    'Abidjan',
    'https://educarriere.ci',
    'published',
    true,
    false,
    timezone('utc', now()) - interval '3 days'
  ),
  (
    'Stagiaire Fibre Optique',
    'stagiaire-fibre-optique-educarriere',
    'Stage terrain pour un profil debutant en installation et support fibre optique.',
    'internship',
    'informatique',
    'Informatique',
    'partner_site',
    'Educarriere.ci',
    'Operateur telecom',
    'Abidjan',
    'https://educarriere.ci',
    'published',
    true,
    false,
    timezone('utc', now()) - interval '1 day'
  ),
  (
    'Stagiaire Aide-Soignant',
    'stagiaire-aide-soignant-aej',
    'Stage pratique pour jeunes diplomes dans le secteur sante.',
    'internship',
    'sante',
    'Sante',
    'institution',
    'Agence Emploi Jeunes',
    'Agence Emploi Jeunes',
    'Yamoussoukro',
    'https://www.emploijeunes.ci',
    'published',
    true,
    false,
    timezone('utc', now()) - interval '4 days'
  )
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  type = excluded.type,
  sector_slug = excluded.sector_slug,
  sector_label = excluded.sector_label,
  source_kind = excluded.source_kind,
  source_name = excluded.source_name,
  organization_name = excluded.organization_name,
  location_city = excluded.location_city,
  external_url = excluded.external_url,
  status = excluded.status,
  is_verified = excluded.is_verified,
  is_premium = excluded.is_premium,
  published_at = excluded.published_at;
